apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka"
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "BROKER:PLAINTEXT"
        - name: KAFKA_LISTENERS
          value: "BROKER://:9092"
        - name: KAFKA_BROKER_ID
          value: "0"
        # - name: KAFKA_LOG_RETENTION_HOURS
        #   value: "168"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "BROKER"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "BROKER://kafka:9092"
        volumeMounts:
          - mountPath: /var/lib/kafka/
            name: kafka-data
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard

--- 
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
  - port: 9092
    protocol: TCP
    nodePort: 30092

