apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: dXNlcl9tYW5hZ2VtZW50      
  postgres-password: dXNlcl9tYW5hZ2VtZW50 
  # DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXJfbWFuYWdlbWVudDp1c2VyX21hbmFnZW1lbnRAdXNlci1tYW5hZ2VtZW50LXBvc3RncmVzOjU0MzIvdXNlcl9tYW5hZ2VtZW50